M48
; DRILL file {KiCad 9.0.6} date 2026-01-05T18:11:24+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-05T18:11:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
%
G90
G05
T1
X8.0743Y-3.9961
T2
X8.9011Y-3.9961
T3
X5.9941Y-3.3268
X5.9941Y-4.0945
X7.5039Y-3.3307
M30
